find_path(GUILE_INCLUDE_DIR libguile.h PATH_SUFFIXES
  guile/2.2
  guile/2.0
  guile/1.8
  guile)

find_library(GUILE_LIBRARY NAMES guile-2.2 guile-2.0 guile-1.8 guile)

if(GUILE_INCLUDE_DIR)
  set(GUILE_VERSION_MAJOR 0)
  set(GUILE_VERSION_MINOR 0)
  set(GUILE_VERSION_PATCH 0)

  file(READ "${GUILE_INCLUDE_DIR}/libguile/version.h" _GUILE_VERSION_H_CONTENTS)

  string(REGEX REPLACE ".*#define SCM_MAJOR_VERSION +([0-9]+).*" "\\1" GUILE_VERSION_MAJOR "${_GUILE_VERSION_H_CONTENTS}")
  string(REGEX REPLACE ".*#define SCM_MINOR_VERSION +([0-9]+).*" "\\1" GUILE_VERSION_MINOR "${_GUILE_VERSION_H_CONTENTS}")
  string(REGEX REPLACE ".*#define SCM_MICRO_VERSION +([0-9]+).*" "\\1" GUILE_VERSION_PATCH "${_GUILE_VERSION_H_CONTENTS}")

  set(GUILE_VERSION "${GUILE_VERSION_MAJOR}.${GUILE_VERSION_MINOR}.${GUILE_VERSION_PATCH}")
endif(GUILE_INCLUDE_DIR)

set(GUILE_LIBRARIES ${GUILE_LIBRARY})
set(GUILE_INCLUDE_DIRS ${GUILE_INCLUDE_DIR})

include(FindPackageHandleStandardArgs)
find_package_handle_standard_args(Guile REQUIRED_VARS GUILE_INCLUDE_DIRS GUILE_LIBRARIES VERSION_VAR GUILE_VERSION)
